services:
  auction-server:
    network_mode: host
    environment:
      DN_ADDRESS: 127.0.0.1:8080
      DN_CLIENT_TOKEN: ""
      DN_OBSERVER_TOKEN: ""
      DN_FABRIC_TOKEN: ""
    volumes:
      - ./data:/data

  order-collector:
    network_mode: host
    volumes:
      - ./collector/accounts.json:/run/secrets/collector-accounts.json:ro
      - ./collector/order-schemas.json:/app/order-schemas.json:ro
      - ./collector/profiles:/data/profiles
      - ./collector/captures:/app/captures
